import { AssetType } from "@/components/Asset";

export const cleanAssets: AssetType[] = [
  {
    id: 0,
    name: "Bitcoin",
    quantity: 0.0863,
    notes: "To the moon!",
    type: "crypto",
    abb: "btc",
    value: 8760,
    baseValue: 80000,
    isDeleted: false,
  },
  {
    id: 1,
    name: "Ethereum",
    quantity: 0.1623,
    notes: "",
    type: "crypto",
    abb: "eth",
    value: 630,
    baseValue: 2856,
    isDeleted: false,
  },
  {
    id: 2,
    name: "Solana",
    quantity: 6.49,
    notes: "",
    type: "crypto",
    abb: "sol",
    value: 1070,
    baseValue: 118,
    isDeleted: false,
  },
  {
    id: 4,
    name: "Silver",
    quantity: 754,
    notes: "",
    type: "metals",
    abb: "silver",
    value: 37700,
    baseValue: 50,
    isDeleted: false,
  },
  {
    id: 5,
    name: "Gold",
    quantity: 3.955,
    notes: "Almost 4!",
    type: "metals",
    abb: "gold",
    value: 14238,
    baseValue: 3600,
    isDeleted: false,
  },
  {
    id: 6,
    name: "Gold ETC",
    quantity: 1,
    notes: "",
    type: "stocks",
    abb: "4GLD.DE",
    value: 14300,
    baseValue: 1900,
    isDeleted: false,
  },
  {
    id: 7,
    name: "ETFs",
    quantity: 1,
    notes: "Nasdaq, Health, Dividend, Commodities",
    type: "stocks",
    abb: "ETF",
    value: 3700,
    baseValue: 1900,
    isDeleted: false,
  },
];
